Add more resources
scala-ukraine/knowledge-base pull request #1
Opened 2022-06-19 16:32 UTC by DenisLobur

- More books
- More courses
- More videos & tutorials

2022-06-19 18:26 UTC, VladKopanev requested changes

2022-06-19 18:26 UTC, VladKopanev commented on README.md
> +### :art: Блоги та інш.
Тепер коли змінівся anchor, посилання в розділі Table of Contents на блоги більше не клікабельно, треба пофіксати.

2022-06-19 18:26 UTC, VladKopanev commented on README.md
> +    <li><a href="https://twitter.github.io/effectivescala/">Effective Scala by Twitter</a></li>
Я б додав ще [Kubuszok](https://kubuszok.com/tags/#scala)
Та [This Week In Scala](https://medium.com/disney-streaming/tagged/thisweekinscala)

2022-06-20 10:19 UTC, VladKopanievExt approved these changes
LGTM

2022-06-20 10:20 UTC, VladKopanev approved these changes
LGTM

2022-06-20 10:20 UTC, merged